<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Astra.Core\Astra.Core.csproj" />
    <ProjectReference Include="..\..\src\Astra.Providers\Astra.Providers.csproj" />
  </ItemGroup>

</Project>
